id = Project.create(title: 'Семья')
Todo.create(text: 'Купить молоко', isCompleted: false, project: id )
Todo.create(text: 'Заменить масло в двигателе до 23 апреля', isCompleted: false, project: id )
Todo.create(text: 'Отправить письмо бабушке', isCompleted: true, project: id )
Todo.create(text: 'Заплатить за квартиру', isCompleted: false, project: id )
Todo.create(text: 'Забрать обувь из ремонта', isCompleted: false, project: id )
id = Project.create(title: 'Работа')
Todo.create(text: 'Позвонить заказчику', isCompleted: true , project: id )
Todo.create(text: 'Отправить документы', isCompleted: true , project: id )
Todo.create(text: 'Заполнить отчет', isCompleted: false, project: id )
id = Project.create(title: 'Прочее')
Todo.create(text: 'Позвонить другу', isCompleted: false, project: id )
Todo.create(text: 'Подготовиться к поездке', isCompleted: false, project: id )

